environment:
  nodejs_version: "14"
install:
    # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - yarn test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101